### PR TITLE
Windguru API accepted units for wind speed

### PR DESCRIPTION
**Pull request by gingibash**
Windguru API accepts only knots as units for wind speed

### CODE REVIEW

**Comment by leoherzog** [comment]
Thanks for your pull request!

I'm currently using knots when I send data to WindGuru.

https://github.com/leoherzog/WundergroundStationForwarder/blob/v2.3.0.1/code.gs#L697-L698

As far as Wind Lull goes, we'd want to have each of the services that we pull _from_ cache that reading, if there is one... I just went through the API docs for each of the other services and it doesn't look like Wunderground, MyAcurite, WeatherLink, or Ambient Weather have lull. I guess only Tempest has it.

**Comment by gingibash** [comment]
@leoherzog weatherflow API always givea data in SI units, which for wind speed is meters per second. Added function to convert m/s to knots.

**Comment by leoherzog** [comment]
Yeah. I've been using "mps" to mean "meters per second", and each of the five data sources has an "mps" and "mph". It looks like I'm missing Knots from a couple of the data sources. So the real goal of this pull request should be to add Knots to the data sources where it's missing.

According to [the WindGuru documentation](https://stations.windguru.cz/upload_api.php), they take in wind speed in Knots.

**Comment by leoherzog** [comment]
I just added the missing knots values in 7510205bd6f4509ca88af8f9d1f08aa30c45badf. Does this fix the issue that you were trying to solve with this PR @gingibash?

**Pull request closed without merging**
