### PR TITLE
Windguru - send time of measurement

### PR DESCRIPTION
**Pull request by vhornik**
WG upload API now supports sending the time of measurement

### CODE REVIEW

**Comment by leoherzog** [comment]
Fantastic! Thanks so much!

**Comment by vhornik** [comment]
Thanks for your script! :-) I am glad to mention it at https://stations.windguru.cz now

**Comment by leoherzog** [comment]
Oh wow, you're the creator of Windguru! Thanks for your service. Do you get many weather station contributions with the user agent `Mozilla/5.0 (compatible; Google-Apps-Script; beanserver; +https://script.google.com; id: UA...)`? I don't have a good way to measure how popular this script is with the distributed copy-paste nature of how it's built.

**Comment by rubengte** [comment]
Well deserved mention 🙌
This script is indeed a brilliant work of art ✨😉

**Comment by vhornik** [comment]
> Oh wow, you're the creator of Windguru! Thanks for your service. Do you get many weather station contributions with the user agent `Mozilla/5.0 (compatible; Google-Apps-Script; beanserver; +https://script.google.com; id: UA...)`? I don't have a good way to measure how popular this script is with the distributed copy-paste nature of how it's built.

thanks! :-) quick check in the logs show about 30 hits per minute
not great, not terrible :-) 
I am sure it will grow up! :-)

**Comment by leoherzog** [comment]
Neat! Thanks.

**Comment by rubengte** [comment]
@leoherzog is it possible to have just the line of code that changed instead of having to copy the whole code?

Since i also have that custom code embedded you created for me to exclude "aberration readings" from Wunderground 🙏

**Comment by leoherzog** [comment]
https://github.com/leoherzog/WundergroundStationForwarder/compare/v2.8.1...v2.8.2

**Comment by rubengte** [comment]
Thank you

**Pull request merged**
